---
version: '2.1'
volumes:
  postgres: {}
  index: {}
  localdata: {}
services:
  ice:
    build: .
    image: jbei/ice:latest
    restart: always
    links:
      - postgres
    ports:
      - '127.0.0.1:9999:8080'
    volumes:
      - index:/var/lib/ice/lucene
      - localdata:/usr/local/tomcat/data
  postgres:
    image: library/postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: ice
      POSTGRES_PASSWORD: icepass
      POSTGRES_USER: iceuser
    volumes:
      - postgres:/var/lib/postgresql/data
    logging:
      driver: 'json-file'
      options:
        max-size: 1m
        max-file: '5'
    expose:
      - '5432'
