package org.jbei.ice.client.common.widget;

/**
 * Font awesome icons that are used in this application. Note that this does not
 * represent a complete list of the icons that are available.
 *
 * @author Hector Plahar
 */
public enum FAIconType {

    ARROW_RIGHT("fa fa-arrow-right"),
    BAN_CIRCLE("fa fa-ban-circle"),
    BAR_CHART("fa fa-bar-chart"),
    BOOK("fa fa-book"),
    BOOKMARK("fa fa-bookmark"),
    BOOKMARK_EMPTY("fa fa-bookmark-empty"),
    BRIEFCASE("fa fa-briefcase"),
    BULLHORN("fa fa-bullhorn"),
    CALENDAR("fa fa-calendar"),
    CAMERA("fa fa-camera"),
    CAMERA_RETRO("fa fa-camera-retro"),
    CARET_DOWN("fa fa-caret-down"),
    CARET_LEFT("fa fa-caret-left"),
    CARET_RIGHT("fa fa-caret-right"),
    CARET_UP("fa fa-caret-up"),
    CHECK("fa fa-check"),
    CHECK_SQUARE("fa fa-check-square"),
    CHEVRON_DOWN("fa fa-chevron-down"),
    CHEVRON_LEFT("fa fa-chevron-left"),
    CHEVRON_CIRCLE_LEFT("fa fa-chevron-circle-left"),
    CHEVRON_RIGHT("fa fa-chevron-right"),
    CHEVRON_CIRCLE_RIGHT("fa fa-chevron-circle-right"),
    CHEVRON_UP("fa fa-chevron-up"),
    CIRCLE_ARROW_DOWN("fa fa-circle-arrow-down"),
    CIRCLE_ARROW_LEFT("fa fa-circle-arrow-left"),
    CIRCLE_ARROW_RIGHT("fa fa-circle-arrow-right"),
    CIRCLE_ARROW_UP("fa fa-circle-arrow-up"),
    COG("fa fa-cog"),
    COGS("fa fa-cogs"),
    COMMENTS_ALT("fa fa-comments-o"),
    COPY("fa fa-copy"),
    CUT("fa fa-cut"),
    DOWNLOAD("fa fa-download"),
    EDIT("fa fa-edit"),
    ENVELOPE("fa fa-envelope"),
    ENVELOPE_ALT("fa fa-envelope-o"),
    EXCLAMATION_TRIANGLE("fa fa-exclamation-triangle"),
    EXTERNAL_LINK("fa fa-external-link"),
    EYE_CLOSE("fa fa-eye-close"),
    EYE_OPEN("fa fa-eye-open"),
    FAST_BACKWARD("fa fa-fast-backward"),
    FAST_FORWARD("fa fa-fast-forward"),
    FILE("fa fa-file"),
    FILTER("fa fa-filter"),
    FOLDER("fa fa-folder"),
    FOLDER_ALT("fa fa-folder-o"),
    FOLDER_OPEN("fa fa-folder-open"),
    FOLDER_OPEN_ALT("fa fa-folder-open-o"),
    FONT("fa fa-font"),
    FORWARD("fa fa-forward"),
    GEAR("fa fa-gear"),
    GLASS("fa fa-glass"),
    GLOBE("fa fa-globe"),
    GROUP("fa fa-group"),
    HDD("fa fa-hdd"),
    INBOX("fa fa-inbox"),
    INDENT_LEFT("fa fa-indent-left"),
    INDENT_RIGHT("fa fa-indent-right"),
    INFO_CIRCLE("fa fa-info-circle"),
    ITALIC("fa fa-italic"),
    KEY("fa fa-key"),
    LEAF("fa fa-leaf"),
    LEGAL("fa fa-legal"),
    LEMON("fa fa-lemon"),
    LINK("fa fa-link"),
    LIST("fa fa-list"),
    LOCK("fa fa-lock"),
    MAGNET("fa fa-magnet"),
    MINUS("fa fa-minus"),
    MINUS_SIGN("fa fa-minus-sign"),
    MOVE("fa fa-move"),
    MUSIC("fa fa-music"),
    OFF("fa fa-off"),

    PAPER_CLIP("fa fa-paperclip"),
    PASTE("fa fa-paste"),
    PAUSE("fa fa-pause"),
    PENCIL("fa fa-pencil"),
    PLUS("fa fa-plus"),
    PLUS_CIRCLE("fa fa-plus-circle"),
    QUESTION_SIGN("fa fa-question-sign"),
    QUOTE_LEFT("fa fa-quote-left"),
    QUOTE_RIGHT("fa fa-quote-right"),
    REFRESH("fa fa-refresh"),
    REORDER("fa fa-reorder"),
    REPEAT("fa fa-repeat"),
    SAVE("fa fa-save"),
    SEARCH("fa fa-search"),
    SHARE("fa fa-share"),
    SHARE_SQUARE("fa fa-share-square"),
    SHIELD("fa fa-shield"),
    SHOPPING_CART("fa fa-shopping-cart"),
    SIGN_BLANK("fa fa-sign-blank"),
    SIGNAL("fa fa-signal"),
    SIGNIN("fa fa-sign-in"),
    SIGNOUT("fa fa-sign-out"),
    SORT("fa fa-sort"),
    SORT_DOWN("fa fa-sort-down"),
    SORT_UP("fa fa-sort-up"),
    STEP_BACKWARD("fa fa-step-backward"),
    STEP_FORWARD("fa fa-step-forward"),
    STOP("fa fa-stop"),
    TABLE("fa fa-table"),
    TAG("fa fa-tag"),
    TAGS("fa fa-tags"),
    TASKS("fa fa-tasks"),
    TH_LIST("fa fa-th-list"),
    THUMB_TACK("fa fa-thumb-tack"),
    TIMES("fa fa-times"),
    TIMES_CIRCLE("fa fa-times-circle"),
    TRASH("fa fa-trash-o"),
    UNDO("fa fa-undo"),
    UNLOCK("fa fa-unlock"),
    UNLOCK_ALT("fa fa-unlock-o"),
    UPLOAD("fa fa-upload"),
    USER("fa fa-user"),
    WARNING("fa fa-warning"),
    WRENCH("fa fa-wrench");

    private String styleName;

    FAIconType(String styleName) {
        this.styleName = styleName;
    }

    public String getStyleName() {
        return styleName;
    }
}
